const {JWT_SECRET, JWT_REFRESH_SECRET, JWT_SECRET_TIME, JWT_REFRESH_SECRET_TIME} = require('../configs');


module.exports = {
  JWT_SECRET: JWT_SECRET,
  JWT_REFRESH_SECRET: JWT_REFRESH_SECRET,
  JWT_SECRET_TIME: JWT_SECRET_TIME,
  JWT_REFRESH_SECRET_TIME: JWT_REFRESH_SECRET_TIME
};
